name: flutter_custom_cards
description: Flutter Custom Cards help developers to create beautiful custom cards and 3D cards with flutter.
version: 0.2.1
homepage: https://github.com/pktintali/
repository: https://github.com/pktintali/flutter_custom_cards

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: