name: flutter_custom_cards
description: New Flutter package which helps developers to create beautiful custom cards.
version: 0.1.0
homepage: https://github.com/pktintali/
repository: https://github.com/pktintali/flutter_custom_cards

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: